version: 2.1

orbs:
  node: circleci/node@5.1.0

parameters:
  flag:
    type: boolean
    default: false

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: 
          environment:
            PARAM_FLAG: << pipeline.parameters.flag >>
          command: echo "hi $PARAM_FLAG"
      - run: 
          environment:
            PARAM_FLAG: << pipeline.parameters.flag >>
          command: ./paramScript << pipeline.parameters.flag >>
workflows:
    workflow1:
      jobs:
        - build