version: 2.1

orbs:
  node: circleci/node@5.1.0

parameters:
  environment:
    type: enum
    enum: [dev, staging, prod]
    default: dev
  service:
    description: Name of the service
    type: string
    default: ""

workflow_condition1: &workflow_condition1
  when:
    and:
      - or:
        - equal: [ dev, << pipeline.parameters.service >> ]
      - not: ["",  << pipeline.parameters.service >> ]

staging_condition: &staging_condition
  when:
    and:
      - equal: [ staging, << pipeline.parameters.environment >> ]
      - not: ["",  << pipeline.parameters.service >> ]

prod_condition: &prod_condition
  when:
    and:
      - equal: [ prod, << pipeline.parameters.environment >> ]
      - not: ["",  << pipeline.parameters.service >> ]

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "hi"
  build2:
    executor: node/default
    steps:
      - checkout
      - run: echo "hi2"
  build3:
    executor: node/default
    steps:
      - checkout
      - run: echo "hi3"

workflows:
  workflow1:
    # <<: *workflow_condition1
    jobs:
      - build
  workflow2:
    # <<: *workflow_condition2
    jobs:
      - build2
  workflow3:
    # <<: *workflow_condition3
    jobs:
      - build3