version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.6

jobs:
  build:
    docker:
      - image: cimg/base:stable
    parallelism: 50
    resource_class: medium
    steps:
      # Checkout the repository files
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: 116.0.5845.96
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            firefox --version
            geckodriver --version
            chromedriver --version
            java -jar /usr/local/bin/selenium.jar --version
          name: Check install

workflows:
  build-workflow:
    jobs:
      - build