version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: small 
    steps: 
      - checkout
      - run:
          name: trigger project b's pipeline
          command: |
            export PIPELINE_ID=$(curl --location --request POST 'https://circleci.com/api/v2/project/github/jkzilla/cci-demo101b/pipeline' \
              --header 'Content-Type: application/json' \
              --header "Circle-Token: ${CIRCLE_TOKEN}" \
            | jq -r '.id')
            echo $PIPELINE_ID >> pipelineId.txt
            echo 'export PIPELINE_ID=$(cat pipelineId.txt)' >> $BASH_ENV
            cat $BASH_ENV
            # curl --location --request POST 'https://circleci.com/api/v2/project/gh/jkzilla/circleci-demo-javascript-react-app/envvar' \
            #   --header 'Content-Type: application/json' \
            #   --header "Circle-Token: ${CIRCLE_TOKEN}" \
            #   --data-raw '{
            #     "name": "PIPELINE_ID",
            #     "value": "$PIPELINE_ID"
            #   }'
      - run:
          name: poll for project b's pipeline status
          command: |
              echo $PIPELINE_ID
              cat $BASH_ENV
              # STATUS=$(curl "https://circleci.com/api/v2/pipeline/$PIPELINE_ID/workflow?circle-token=$CIRCLE_TOKEN" | jq -r '.items[].status')
              # while [ "$STATUS" == "running" ]; do
              #   echo still running
              #   sleep 10
              #   STATUS=$(curl "https://circleci.com/api/v2/pipeline/$PIPELINE_ID/workflow?circle-token=$CIRCLE_TOKEN" | jq -r '.items[].status')
              # done
              # echo "finally done, checking final status: $STATUS"
              # if [[ "$STATUS" == "success" ]]; then
              #   echo "Proceeding with build, as triggered pipeline was success"
              #   exit 0
              # else
              #   echo "Stopping build, triggered pipeline was not a success"
              #   exit 1
              # fi
workflows:
  workflow:
    jobs:
      - build: 
          context: CIRCLE_TOKEN
      

# VS Code Extension Version: 1.1.1