version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.06
    resource_class: arm.medium
    steps:
      - checkout
      - run: echo "hi"

workflows:
  workflow1:
    jobs:
      - build