version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_TAG: docker/scout-demo-service:latest
    resource_class: jkzilla/container-runner
    steps:
      - checkout
      - run: echo "Hi I'm on Runner!"

workflows:
  build-workflow:
    jobs:
      - build