version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.01
    resource_class: small 
    steps: 
      - checkout
      - run:
          name: install firebase
          command: |
            curl -sL https://firebase.tools | bash
      - run:
          name: check firebase
          command: |
            firebase login

workflows:
  scheduled-workflow:
    triggers:
      - schedule:
        # Run every 2 hours
          cron: "* 0,2,4,6,8,10,12,14,16,18,20,22, * * *"
          filters:
            branches:
                only: master
    jobs:
      - build
            