orbs:
  node: circleci/node@4.2.1
  gcp-cli: circleci/gcp-cli@2.2.0 

version: 2.1

jobs:
   build:
      docker:
        - image: docker
      steps:
        - checkout
        - gcp-cli/install
        - run:
            name: test gcloud
            command: |
              gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json


workflows:
  app-tests:
    jobs:
      - build
