version: 2.1
jobs:
  build:
    circleci_ip_ranges: true # opts the job into the IP ranges feature
    docker:
      - image: cimg/node:18.4.0
    # parallelism: 40
    steps:
      - run:
          command: |
            sudo apt-get -y update && apt-get install dnsutils -y
            # sudo yum install bind-utils
workflows:
  build-workflow:
    jobs:
      - build