version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.11
    resource_class: jkzilla/container-runner
    steps:
      - checkout
      - run: echo "Hi I'm on Runner!"

workflows:
  build-workflow:
    jobs:
      - build