version: 2.1

orbs:
  node: circleci/node@5.1.0

parameters:
  service:
    type: enum
    enum: [dev, report]
    default: dev

workflow_condition1: &workflow_condition1
  when:
    and:
      - or:
        - equal: [ dev, << pipeline.parameters.service >> ]
      - not: ["",  << pipeline.parameters.service >> ]

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "hi"

workflows:
  workflow1:
    # <<: *workflow_condition1
    jobs:
      - build